### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by christophfink** [aardsoft/cups-email#1]
Hi!

Thanks for this simple but effective PPD. I’ve been using it for a bit now and would like to add it to the Arch Linux user repository (AUR), mainly for my own convenience. 

**Could you specify which license this PPD is under?** I need to add that information to the package. The project you forked form is GPLv2, so I guess your code is, too?

Kiittos!

**Comment by bwachter** [comment]
I've just added the GPLv2 license file.

**Comment by christophfink** [comment]
thanks!
