### ISSUE TITLE
Printer device falls over on clicking Add Printer

### ISSUE THREAD

**Issue by monk-insane** [aardsoft/cups-email#2]
Hi there,

The email printer device fails to load with cups, when clicking add printer. 

CUPS error log states:

PID 10278 (email) stopped with status 1!

Cups version 2.3.1 running on Ubuntu 20.04 LTS

**Comment by bwachter** [comment]
Try creating a printer via CLI first to rule out user error during filling of the web forms:

lpadmin -p email-sample -E -v email:/sample -D 'Sample email printer' -L 'Over there.' -m email.ppd

If that doesn't work, enable debug logging in cups (LogLevel debug2 in /etc/cups/cupsd.conf), try again, and paste the output.

**Comment by monk-insane** [comment]
First-off thanx for the assist,

I've enabled debug mode and log file attached.

Complains about bad variable smtp-auth

I can however add the printer command line:

root@X2Go-App-Server:/usr/lib/cups/backend# lpadmin -p email-sample -E -v email:/sample -D 'Sample email printer' -L 'Over there.' -m email.ppd
lpadmin: Printer drivers are deprecated and will stop working in a future version of CUPS.

running the script directly yields the following:

root@X2Go-App-Server:/usr/lib/cups/backend# ./email
virtual email "Unknown" "E-Mail Device"
./email: 67: export: smtp-auth: bad variable name
root@X2Go-App-Server:/usr/lib/cups/backend# mailx
No mail for root



[cupserrorlog.txt](https://github.com/aardsoft/cups-email/files/4603707/cupserrorlog.txt)


Printing test page yields "awaiting authentication" In the job status

**Comment by bwachter** [comment]
I assume you have a queue configuration file with smtp-auth settings? I've never used that myself due to having my own local mailservers which just allow mail from IP ranges.

I'd recommend putting the smtp-auth settings into a mailrc file, and specifying the mailrc file in the queue settings.

I did push some minor fixes to error logging yesterday, you'll probably want to grab that.

**Comment by bwachter** [comment]
I also just pushed a major rewrite of the script, which moves all error checking into the print queue when jobs are coming in, not at creation time, and significantly improves on the error reporting (if an error happens it'll halt the print queue, and you should find sensible error messages in the failed job and the paused printer). 

This also gets rid of the queue specific configuration file, and accepts configuration through the CUPS UI (documentation for that is only partially finished yet). You'd still need to have the mailrc file for smtp-auth (smtp server without auth can be set directly, but I didn't add auth details that way as they'd be user visible).

**Comment by monk-insane** [comment]
> I also just pushed a major rewrite of the script, which moves all error checking into the print queue when jobs are coming in, not at creation time, and significantly improves on the error reporting (if an error happens it'll halt the print queue, and you should find sensible error messages in the failed job and the paused printer).
> 
> This also gets rid of the queue specific configuration file, and accepts configuration through the CUPS UI (documentation for that is only partially finished yet). You'd still need to have the mailrc file for smtp-auth (smtp server without auth can be set directly, but I didn't add auth details that way as they'd be user visible).

Wow Thank you!

Will grab the new version and give that a try! I see you've updated the docs as well. Nice! 

Quick Question,  I'm using ssmtp on this particular server, any way to have the printer relay mail through ssmtp instead of sending out directly?  It basically just needs to send using mail without specifying the server details - and it should get send via ssmtp. (like you'd manually send mail from cli  - for example: echo "test" | mailx -s "Test mail" someone@gmail.com ). If not - all good as well. :)

Thank you very much for the assistance and effort.

**Comment by bwachter** [comment]
> Quick Question, I'm using ssmtp on this particular server, any way to have the printer relay mail through ssmtp instead of sending out directly?

Just don't configure the smtp server, and mailx will fall back to using a local sendmail, which in your case should be a link to ssmtp. This configuration will also work without a mailrc, and can now be configured fully from the CUPS UI.

You should carefully test the behaviour when ssmtp fails to deliver the mail - it does (or used to) not have any local queuing, so tends to lose mails on submission errors. For that reason I've replaced ssmtp on my systems with my own minimalistic smtp client with sendmail wrapper about 15 years ago. For a correct behaviour (like mailx would behave with a smtp server configured) you should get the delivery error message in the printer and job status, and have the printer either halted, or the job retried until sending succeeds, depending on how you configured the queue.

**Comment by monk-insane** [comment]
Thanx! 

Just FYI - Ubuntu 20.04 replaced heirloom mailx with s-nail. Installing mailutils package installs gun-mailutils -
and the version of mailx in there does not have the smtp options.

Solution in this case is to install s-nail and create a symbolic link from /usr/bin/mailx to /usr/bin/s-nail

Why I have been having so many issues. sigh.

**Comment by bwachter** [comment]
> Solution in this case is to install s-nail and create a symbolic link from /usr/bin/mailx to /usr/bin/s-nail

Overriding mailx is already supported - if you use the makefile, `make MAILX=/usr/bin/s-nail install` should install everything with the ppd pointing to your mailx. Alternatively you can manually edit the ppd before installing. 

All the basic options are supported in GNU's mailx, so if you go for the ssmtp variant where delivery happens through sendmail it most likely should also work with that one - not tested by me, though, after all the initial motivation of writing this was to not use GNUs mailx :)

Note that I've never tried to use those scripts on Ubuntu - they tend to do a few things a bit different, so it's not surprising there are some issues. I did verify it with a similar cups version than you're using yesterday, though (my print server still has a previous cups release).

**Comment by monk-insane** [comment]
OK I've got everything set up - but am still getting "Held for Authentication" in the job status page on cups

Getting this in the cups error log: 

[Client 1419] Returning IPP client-error-not-authorized for Print-Job (ipp://localhost:631/printers/Email) from localhost.

![2020-05-11 13_27_07-Jobs - CUPS 2 3 1](https://user-images.githubusercontent.com/37340691/81556786-30ff5b00-938b-11ea-985d-f65a1948bd84.png)

**Comment by bwachter** [comment]
How are you printing to it? To avoid any authentication issues, try the first prints with lpr as root from the cups server itself (described in the documentation). If that also throws the authentication error you should paste the debug log for the job.

**Comment by monk-insane** [comment]
Printing a test page from cups admin page - soz above error was caused by me fiddling with allowed users. I believe Ive found the issue  - check the last couple of lines on this error log.

D [11/May/2020:13:46:46 +0200] [Job 26] /usr/lib/cups/backend/email: 53: Syntax error: \"(\" unexpected
D [11/May/2020:13:46:46 +0200] PID 38224 (/usr/lib/cups/cgi-bin/printers.cgi) exited with no errors.
D [11/May/2020:13:46:46 +0200] [Job 26] PID 38228 (/usr/lib/cups/backend/email) stopped with status 2.
D [11/May/2020:13:46:46 +0200] [Client 98] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [11/May/2020:13:46:46 +0200] [Client 98] Closing connection.


It's complaining about this line in email backend script: 
function getOptionFromPpd(){

but for the life of me can't figure out why - it looks fine to me.

[cupserrorlog.txt](https://github.com/aardsoft/cups-email/files/4609350/cupserrorlog.txt)

**Comment by bwachter** [comment]
I think /bin/sh on Debian might be some tiny shell, not a bash, and therefore is complaining about the bash style function declaration. I've just pushed a change explicitly using bash.

**Comment by monk-insane** [comment]
hah! Changed the shell declaration in /usr/lib/cups/backend/email from #! /bin/sh to #! /bin/bash - works now! Whoohoo!!!

Oh, and FYI - printing via ssmtp is working as well, not using mailrc in /etc/cups

Thanx for the assistance! Much appreciated!
