### ISSUE TITLE
backend / mailrc permissions

### ISSUE THREAD

**Issue by atanczos** [aardsoft/cups-email#4]
Leaving authentication data in the `mailrc` file is a security issue, it should be read only by root.
For this the `/usr/lib/cups/backend/email` file should have only 700 permission, but in the `Makefile` you have 755.

**Comment by bwachter** [comment]
Mailrc files need to be manually installed by the user, it's up to the user to give them sensible permissions. 

The email backend doesn't contain any stored credentials, so as long as it's not writeable (and therefore replaceable) by an arbitrary user it's fine.
