### ISSUE TITLE
Doesn't work on archlinux because of mailx

### ISSUE THREAD

**Issue by andybe** [aardsoft/cups-email#8]
Installed mailx & epstopdf

mailx fail by:

Warning: $USER (root) not identical to user (cups)!

and printer stopped.

On which linux distribution the plugin was tested?

**Comment by bwachter** [comment]
Can you add the following lines at the beginning of the script, try to print, and paste the content of the log file here:

export > /tmp/cups-email
id >> /tmp/cups-email

**Comment by bwachter** [comment]
@andybe reminder that I need information from you to look into this.

**Comment by bwachter** [comment]
Closing this issue as original submitter hasn't provided the required information in over a year.
